name: Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup
        run: npm i -g @vtrbo/ni

      - name: Install
        run: nci

      - name: Build
        run: 'nr build'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          # cname: vtrbo.cn
          publish_branch: site
          publish_dir: ./.svelte-kit/output/
          commit_message: Release by
          github_token: ${{secrets.GITHUB_TOKEN}}
